# Generated by Django 3.2.9 on 2021-12-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsreport',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='projectcomments',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projectpictures',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectsreport',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Commentsreport',
        ),
        migrations.DeleteModel(
            name='Projectcomments',
        ),
        migrations.DeleteModel(
            name='Projectpictures',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectsReport',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
