# Generated by Django 3.2.9 on 2021-12-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cat1', 'CATEGORY1'), ('cat2', 'CATEGORY2'), ('cat3', 'CATEGORY3'), ('cat4', 'CATEGORY4'), ('cat5', 'CATEGORY5')], default='cat1', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('Project_id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=50)),
                ('Project_details', models.CharField(max_length=500)),
                ('Total_target', models.IntegerField()),
                ('Total_donations', models.IntegerField()),
                ('Avg_rate', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('tag1', 'TAG1'), ('tag2', 'TAG2'), ('tag3', 'TAG3'), ('tag4', 'TAG4'), ('tag5', 'TAG5')], default='tag1', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_project', models.CharField(max_length=1000)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.tags'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Projectpictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Projectcomments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Commentsreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_comment', models.CharField(max_length=1000)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.projectcomments')),
            ],
        ),
    ]
