# Generated by Django 3.2.9 on 2021-12-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20211203_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Avg_rate',
            new_name='avg_rate',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Project_details',
            new_name='project_details',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Project_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Project_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Total_donations',
            new_name='total_donations',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='Total_target',
            new_name='total_target',
        ),
    ]
