# Generated by Django 3.2.9 on 2021-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_auto_20211203_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomments',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
