# Generated by Django 3.2.9 on 2021-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_alter_projectcomments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_donations',
            field=models.IntegerField(default=0),
        ),
    ]
