# Generated by Django 3.2.9 on 2021-12-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_auto_20211206_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_donations',
            field=models.IntegerField(default=0),
        ),
    ]
