# Generated by Django 3.2.9 on 2021-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_auto_20211206_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='raters',
            field=models.IntegerField(default=0),
        ),
    ]
